import '../styles/globals.css'
import Head from 'next/head'
import Layout from '../components/layouts/Layout'
import { Montserrat } from '@next/font/google'
import Router from "next/router";
import { usePageLoading } from '../hooks/PageLoading';
import Loading from '../components/utils/LoadingCircle'

const montserrat = Montserrat({ subsets: ['latin'] })

export default function App({ Component, pageProps }) {
  const { isPageLoading } = usePageLoading();

  return (
    <>
      <Head>
        <title>Gonsa Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={montserrat.className}>
        <Layout>
          {isPageLoading ? (
            <Loading />
          ) : (
            <Component {...pageProps} />
          )}
        </Layout>
      </main>

    </>
  )
}
